copyright: Copyright &copy; 2024-2024 VRTASS
site_name: MkDocs for Debian on VirtualBox/UTM
site_author: The Virtual Ass

site_description: >
           MkDocs for 
           a Virtual Debian Guest 
           on VirtualBox.
site_url:  https://vrtass.github.io/tester/

nav:
  - Home: index.md
  - Examples: examples.md
  - GitHub: https://github.com/vrtass/tester/
  - WEB: https://vrtass.github.io/tester/

theme:
  name:    material
  font:
    text:  Verdana
    code:  Red Hat Mono
  logo:    img/vrtass.jpg
  favicon: img/favicon.ico
  features:
    - content.code.copy
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      # linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  author:          "The Virtual Ass"
  custom_variable: "This is a custom variable from mkdocs.yml"
  github_url:      "https://github.com/vrtass/tester/"
  social:
    - icon: simple/github
      link: https://github.com/vrtass/tester/

  seo:
    description: >
            MkDocs for 
            a Virtual Debian Guest 
            on VirtualBox.
    keywords: "keyword1, keyword2"

extra_css:
  - assets/styles.css

plugins:
  - awesome-pages
  - include-markdown
  - search
  - macros

# REVISION: Thu 05 Dec 2024 19:00
# REVISION: Thu 05 Dec 2024 15:00
# REVISION: Tue 03 Dec 2024 22:00
# REVISION: Tue 03 Dec 2024 20:00
# REVISION: Tue 03 Dec 2024 16:00
# STARTING: Tue 03 Dec 2024 09:00

